"""Change revision

Revision ID: 7e583455daf3
Revises: 9e2544cfad6c
Create Date: 2025-04-22 15:28:45.509409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e583455daf3'
down_revision: Union[str, None] = '9e2544cfad6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_photo_filename_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_photo_filename_key', 'users', ['photo_filename'])
    # ### end Alembic commands ###
